apiVersion: v1
kind: Secret
metadata:
  name: calculator
type: Opaque
data:
  db_username: cG9zdGdyZXM=  # base64-кодированный "postgres", чтобы зашифровать, можно использовать команду в Git Bash: echo -n "postgres" | base64
  db_password: cG9zdGdyZXM=  # base64-кодированный "postgres"
